discord:
  music-bot:
    channels:
      - music
      - music-request
    inactivity-timeout-seconds: 300
  authentication:
    public:
      app-id: ${DISCORD_APPLICATION_ID}
      guild-id: ${DISCORD_GUILD_ID}
      public-key: ${DISCORD_PUBLIC_KEY}
    secret:
      discord-token: ${DISCORD_BOT_TOKEN}