discord:
  music-bot:
    inactivity-timeout-seconds: 300
  authentication:
    public:
      request-channel-id: ${DISCORD_REQUEST_CHANNEL_ID}
      app-id: ${DISCORD_APPLICATION_ID}
      guild-id: ${DISCORD_GUILD_ID}
      public-key: ${DISCORD_PUBLIC_KEY}
    secret:
      discord-token: ${DISCORD_BOT_TOKEN}
      oauth-2-token: ${OAUTH_2_TOKEN}